// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import type {Collection, SavedRequest, HistoryEntry, Session} from '../../../src/lib/store-types';

export function Export(arg1:main.Request,arg2:Array<any>,arg3:Array<string>,arg4:main.RequestResult):Promise<void>;

export function MakeRequest(arg1:string,arg2:string,arg3:string,arg4:{[key: string]: string}):Promise<main.RequestResult>;

export function RunCurl(arg1:string):Promise<main.RequestResult>;

export function Send(arg1:main.RequestSpec):Promise<main.RequestResult>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function ListCollections():Promise<Collection[]>;

export function SaveCollection(arg1:Collection):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function SaveRequest(arg1:string,arg2:SavedRequest):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string):Promise<void>;

export function AppendHistory(arg1:HistoryEntry):Promise<void>;

export function ListHistory(arg1:number):Promise<HistoryEntry[]>;

export function ClearHistory():Promise<void>;

export function LoadSession():Promise<Session>;

export function SaveSession(arg1:Session):Promise<void>;
