// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1) {
  return window['go']['main']['App']['Export'](arg1);
}

export function MakeRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeRequest'](arg1, arg2, arg3, arg4);
}

export function RunCurl(arg1) {
  return window['go']['main']['App']['RunCurl'](arg1);
}
