// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendHistory(arg1) {
  return window['go']['main']['App']['AppendHistory'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function Export(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Export'](arg1, arg2, arg3, arg4);
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListHistory(arg1) {
  return window['go']['main']['App']['ListHistory'](arg1);
}

export function LoadSession() {
  return window['go']['main']['App']['LoadSession']();
}

export function MakeRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeRequest'](arg1, arg2, arg3, arg4);
}

export function RunCurl(arg1) {
  return window['go']['main']['App']['RunCurl'](arg1);
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SaveRequest(arg1, arg2) {
  return window['go']['main']['App']['SaveRequest'](arg1, arg2);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
